-- ====================================================================
-- Comment Service Schema (Supabase PostgreSQL)
-- ====================================================================
-- Run this in the Supabase Dashboard -> SQL Editor
-- Tables: public.comments
-- ====================================================================

CREATE TABLE IF NOT EXISTS public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    parent_id BIGINT REFERENCES public.comments(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_comments_post_id ON public.comments (post_id);
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON public.comments (user_id);
CREATE INDEX IF NOT EXISTS idx_comments_parent_id ON public.comments (parent_id);

-- Row Level Security (RLS)
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for comments" ON public.comments;
CREATE POLICY "Allow all for comments" ON public.comments 
    FOR ALL TO anon, authenticated 
    USING (true) 
    WITH CHECK (true);
