-- ====================================================================
-- Microservices Blog Platform - Supabase PostgreSQL Schema
-- ====================================================================
-- Run this script in the Supabase Dashboard -> SQL Editor
-- Project URL: https://lygxpdtegrpwaqmthicc.supabase.co
-- ====================================================================

-- 1. Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    hashed_password TEXT NOT NULL,
    full_name TEXT,
    bio TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Posts Table
CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    content TEXT NOT NULL,
    summary TEXT,
    tags JSONB DEFAULT '[]'::jsonb,
    is_published BOOLEAN DEFAULT TRUE,
    is_premium BOOLEAN DEFAULT FALSE,
    price NUMERIC(10, 2) DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Comments Table
CREATE TABLE IF NOT EXISTS public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    parent_id BIGINT REFERENCES public.comments(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Wallets Table
CREATE TABLE IF NOT EXISTS public.wallets (
    user_id BIGINT PRIMARY KEY,
    balance NUMERIC(12, 2) DEFAULT 0.00,
    currency TEXT DEFAULT 'NGN',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Transactions Table
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type TEXT NOT NULL, -- 'topup', 'tip_sent', 'tip_received', 'post_purchase', 'post_sale'
    amount NUMERIC(12, 2) NOT NULL,
    counterparty_id BIGINT,
    reference_id TEXT UNIQUE,
    description TEXT,
    status TEXT DEFAULT 'success', -- 'pending', 'success', 'failed'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Access Passes Table (Purchased Premium Posts)
CREATE TABLE IF NOT EXISTS public.access_passes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    amount_paid NUMERIC(10, 2) DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, post_id)
);

-- Enable Row Level Security (RLS) and grant API access
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.access_passes ENABLE ROW LEVEL SECURITY;

-- Allow read & write access for both anon and authenticated roles
DROP POLICY IF EXISTS "Allow all for users" ON public.users;
CREATE POLICY "Allow all for users" ON public.users FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for posts" ON public.posts;
CREATE POLICY "Allow all for posts" ON public.posts FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for comments" ON public.comments;
CREATE POLICY "Allow all for comments" ON public.comments FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for wallets" ON public.wallets;
CREATE POLICY "Allow all for wallets" ON public.wallets FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for transactions" ON public.transactions;
CREATE POLICY "Allow all for transactions" ON public.transactions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for access_passes" ON public.access_passes;
CREATE POLICY "Allow all for access_passes" ON public.access_passes FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
