-- ====================================================================
-- Payment Service Schema (Supabase PostgreSQL)
-- ====================================================================
-- Run this in the Supabase Dashboard -> SQL Editor
-- Tables: public.wallets, public.transactions, public.access_passes
-- ====================================================================

-- 1. Wallets Table
CREATE TABLE IF NOT EXISTS public.wallets (
    user_id BIGINT PRIMARY KEY,
    balance NUMERIC(12, 2) DEFAULT 0.00,
    currency TEXT DEFAULT 'NGN',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Transactions Table
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type TEXT NOT NULL, -- 'topup', 'tip_sent', 'tip_received', 'post_purchase', 'post_sale'
    amount NUMERIC(12, 2) NOT NULL,
    counterparty_id BIGINT,
    reference_id TEXT UNIQUE,
    description TEXT,
    status TEXT DEFAULT 'success', -- 'pending', 'success', 'failed'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Access Passes Table (Purchased Premium Posts)
CREATE TABLE IF NOT EXISTS public.access_passes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    amount_paid NUMERIC(10, 2) DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, post_id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_tx_user ON public.transactions (user_id);
CREATE INDEX IF NOT EXISTS idx_tx_ref ON public.transactions (reference_id);
CREATE INDEX IF NOT EXISTS idx_passes_user_post ON public.access_passes (user_id, post_id);

-- Row Level Security (RLS)
ALTER TABLE public.wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.access_passes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for wallets" ON public.wallets;
CREATE POLICY "Allow all for wallets" ON public.wallets 
    FOR ALL TO anon, authenticated 
    USING (true) 
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for transactions" ON public.transactions;
CREATE POLICY "Allow all for transactions" ON public.transactions 
    FOR ALL TO anon, authenticated 
    USING (true) 
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for access_passes" ON public.access_passes;
CREATE POLICY "Allow all for access_passes" ON public.access_passes 
    FOR ALL TO anon, authenticated 
    USING (true) 
    WITH CHECK (true);
