-- ====================================================================
-- All Tables - Microservices Blog Platform (Supabase PostgreSQL)
-- ====================================================================
-- Run this in the Supabase Dashboard -> SQL Editor
-- Project: https://lygxpdtegrpwaqmthicc.supabase.co
-- ====================================================================

-- 1. USERS
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    hashed_password TEXT NOT NULL,
    full_name TEXT,
    bio TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_users_username ON public.users (username);
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users (email);
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for users" ON public.users;
CREATE POLICY "Allow all for users" ON public.users FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 2. POSTS
CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    content TEXT NOT NULL,
    summary TEXT,
    tags JSONB DEFAULT '[]'::jsonb,
    is_published BOOLEAN DEFAULT TRUE,
    is_premium BOOLEAN DEFAULT FALSE,
    price NUMERIC(10, 2) DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_posts_slug ON public.posts (slug);
CREATE INDEX IF NOT EXISTS idx_posts_author ON public.posts (author_id);
CREATE INDEX IF NOT EXISTS idx_posts_published ON public.posts (is_published);
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for posts" ON public.posts;
CREATE POLICY "Allow all for posts" ON public.posts FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 3. COMMENTS
CREATE TABLE IF NOT EXISTS public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    parent_id BIGINT REFERENCES public.comments(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_comments_post_id ON public.comments (post_id);
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON public.comments (user_id);
CREATE INDEX IF NOT EXISTS idx_comments_parent_id ON public.comments (parent_id);
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for comments" ON public.comments;
CREATE POLICY "Allow all for comments" ON public.comments FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 4. WALLETS
CREATE TABLE IF NOT EXISTS public.wallets (
    user_id BIGINT PRIMARY KEY,
    balance NUMERIC(12, 2) DEFAULT 0.00,
    currency TEXT DEFAULT 'NGN',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.wallets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for wallets" ON public.wallets;
CREATE POLICY "Allow all for wallets" ON public.wallets FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 5. TRANSACTIONS
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    counterparty_id BIGINT,
    reference_id TEXT UNIQUE,
    description TEXT,
    status TEXT DEFAULT 'success',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_tx_user ON public.transactions (user_id);
CREATE INDEX IF NOT EXISTS idx_tx_ref ON public.transactions (reference_id);
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for transactions" ON public.transactions;
CREATE POLICY "Allow all for transactions" ON public.transactions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 6. ACCESS PASSES
CREATE TABLE IF NOT EXISTS public.access_passes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    amount_paid NUMERIC(10, 2) DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, post_id)
);
CREATE INDEX IF NOT EXISTS idx_passes_user_post ON public.access_passes (user_id, post_id);
ALTER TABLE public.access_passes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for access_passes" ON public.access_passes;
CREATE POLICY "Allow all for access_passes" ON public.access_passes FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
